In [1]:
import torch
from torch import nn
import torch.nn.functional as F

In [6]:
import numpy as np

In [22]:
In = torch.randn(1, 1, 2, 2)
In

tensor([[[[ 0.3283, -0.8489],
          [ 0.4182,  0.0571]]]])

### Sigmoid 函数

In [23]:
f_sigmoid = 1 / (1 + np.exp(-1 * In.numpy()))

In [24]:
sigmoid = nn.Sigmoid()

In [25]:
sigmoid(In)

tensor([[[[0.5813, 0.2997],
          [0.6031, 0.5143]]]])

In [26]:
f_sigmoid

array([[[[0.58134687, 0.29965484],
         [0.6030618 , 0.5142654 ]]]], dtype=float32)

In [27]:
np.zeros(In.numpy().shape)

array([[[[0., 0.],
         [0., 0.]]]])

### ReLU 函数

In [28]:
f_relu = np.maximum(np.zeros(In.numpy().shape), In.numpy())
f_relu

array([[[[0.32830489, 0.        ],
         [0.41823909, 0.05707722]]]])

In [30]:
relu = nn.ReLU()

In [31]:
relu(In)

tensor([[[[0.3283, 0.0000],
          [0.4182, 0.0571]]]])

### Leaky ReLU 函数

In [37]:
f_leaky_relu = np.maximum((.04)*In.numpy(), In.numpy())
f_leaky_relu

array([[[[ 0.3283049 , -0.03395768],
         [ 0.4182391 ,  0.05707722]]]], dtype=float32)

In [34]:
leaky_relu = nn.LeakyReLU()

In [38]:
leaky_relu(In)

tensor([[[[ 0.3283, -0.0085],
          [ 0.4182,  0.0571]]]])

### Softmax 函数

In [39]:
def softmax(x):
    x_exp = np.exp(x)
    #如果是列向量，则axis=0
    x_sum = np.sum(x_exp, axis = 1, keepdims = True)
    s = x_exp / x_sum    
    return s

In [40]:
softmax(In.numpy())

array([[[[1., 1.],
         [1., 1.]]]], dtype=float32)

In [47]:
Softmax = F.softmax(In, 1)

In [48]:
Softmax

tensor([[[[1., 1.],
          [1., 1.]]]])

### tanh 函数

In [49]:
def tanh(x):
    return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x)) 

In [50]:
tanh(In.numpy())

array([[[[ 0.31699684, -0.69051635],
         [ 0.3954459 ,  0.0570153 ]]]], dtype=float32)

In [51]:
Tanh = nn.Tanh() 

In [52]:
Tanh(In)

tensor([[[[ 0.3170, -0.6905],
          [ 0.3954,  0.0570]]]])