In [18]:
import torch
from torch import nn

In [19]:
class Linear(nn.Module):
    # y = wx + b
    def __init__(self, in_dim, out_dim):
        super(Linear, self).__init__()
        self.w = nn.Parameter(torch.randn(in_dim, out_dim))
        self.b = nn.Parameter(torch.randn(out_dim))
    
    def forward(self, x):
        x = x.matmul(self.w)
        y = x + self.b.expand_as(x)
        return y

In [20]:
class Perception(nn.Module):
    def __init__(self, in_dim, hid_dim, out_dim):
        super(Perception, self).__init__()
        self.layer1 = Linear(in_dim, hid_dim)
        self.layer2 = Linear(hid_dim, out_dim)
    
    def forward(self, x):
        x = self.layer1(x)
        y = torch.sigmoid(x)
        y = self.layer2(y)
        y = torch.sigmoid(y)
        return y

In [21]:
perception = Perception(2, 3, 2)

In [22]:
perception

Perception(
  (layer1): Linear()
  (layer2): Linear()
)

In [23]:
for name, parameter in perception.named_parameters():
    print(f'name: {name}, parameter: {parameter}')

name: layer1.w, parameter: Parameter containing:
tensor([[ 0.2676, -0.3342,  0.5117],
        [-0.1016,  1.2790,  1.4075]], requires_grad=True)
name: layer1.b, parameter: Parameter containing:
tensor([-0.7289,  0.9349,  0.3367], requires_grad=True)
name: layer2.w, parameter: Parameter containing:
tensor([[-0.6178,  0.3433],
        [ 1.1033, -1.4031],
        [-0.2202, -1.4048]], requires_grad=True)
name: layer2.b, parameter: Parameter containing:
tensor([-0.1971,  3.1075], requires_grad=True)


In [24]:
data = torch.randn(4, 2)
data

tensor([[ 0.7602, -0.5524],
        [ 0.3414,  0.3066],
        [-0.9396, -0.1493],
        [-0.2099, -0.4687]])

In [25]:
out = perception(data)

In [26]:
out

tensor([[0.5006, 0.8656],
        [0.5709, 0.7561],
        [0.5892, 0.8294],
        [0.5444, 0.8609]], grad_fn=<SigmoidBackward>)

In [27]:
out.detach()

tensor([[0.5006, 0.8656],
        [0.5709, 0.7561],
        [0.5892, 0.8294],
        [0.5444, 0.8609]])

In [28]:
out.grad_fn

In [30]:
class Perception(nn.Module):
    def __init__(self, in_dim, hid_dim, out_dim):
        super(Perception, self).__init__()
        self.layer = nn.Sequential(
            Linear(in_dim, hid_dim),
            nn.Sigmoid(),
            Linear(hid_dim, out_dim),
            nn.Sigmoid()
        )
    
    def forward(self, x):
        y = self.layer(x)
        return x

In [31]:
model = Perception(100, 1000, 10).cuda()

In [32]:
model

Perception(
  (layer): Sequential(
    (0): Linear()
    (1): Sigmoid()
    (2): Linear()
    (3): Sigmoid()
  )
)

In [39]:
data = torch.randn(100).cuda()

In [40]:
out = model(data)

In [41]:
out

tensor([ 8.5738e-01, -1.0528e+00, -2.1495e+00,  1.5033e+00, -4.1807e-01,
         3.8394e-01,  6.4068e-01, -1.5589e-01, -5.9191e-01, -3.6435e-01,
        -7.3422e-01, -2.9891e-01,  6.3815e-01,  1.8540e+00, -5.4919e-01,
         8.1691e-01, -8.0972e-03,  1.9923e-01,  6.1462e-01,  9.9960e-01,
         8.5726e-01, -7.7424e-01, -6.1987e-01, -6.4704e-02, -4.2537e-01,
         1.6725e+00,  4.4642e-01, -7.0841e-01, -1.0394e+00,  1.3815e-01,
        -1.3225e+00,  1.0190e+00, -1.8861e+00,  8.8450e-01, -1.3578e+00,
        -1.3768e+00,  4.5914e-01, -1.9178e+00,  5.6636e-01,  1.5538e+00,
         5.5115e-01, -3.8460e-02,  7.7326e-01,  6.1811e-01, -1.6003e+00,
         4.0716e-01, -3.1748e-01, -1.0143e+00,  1.0260e+00, -1.3431e-02,
        -1.5298e+00,  4.0522e-04, -9.0276e-01, -4.5830e-02, -1.6845e+00,
        -2.3788e-01, -4.2126e-02,  5.0658e-01, -8.0982e-01, -4.1677e-01,
         4.6649e-01, -6.7815e-01,  2.5337e-02, -4.6371e-01, -6.7439e-01,
        -2.2401e+00, -1.6220e+00, -7.6685e-01, -5.1