In [1]:
import torch

In [2]:
x = torch.randn(1)
w = torch.ones(1, requires_grad=True)
b = torch.ones(1, requires_grad=True)

In [7]:
w

tensor([1.], requires_grad=True)

In [8]:
x.is_leaf

True

In [9]:
y = w * x

In [10]:
y

tensor([0.4875], grad_fn=<MulBackward0>)

In [12]:
z = y + b
z

tensor([1.4875], grad_fn=<AddBackward0>)

In [13]:
y.is_leaf

False

In [14]:
y.requires_grad

True

In [15]:
y.grad_fn

In [16]:
z

tensor([1.4875], grad_fn=<AddBackward0>)

In [18]:
z.backward(retain_graph=True)

In [19]:
z

tensor([1.4875], grad_fn=<AddBackward0>)

In [21]:
w.grad

tensor([0.4875])

In [22]:
b.grad

tensor([1.])