In [2]:
import torch
from torch import nn
import torch.nn.functional as F
import numpy as np

### Pooling

In [3]:
max_pooling = nn.MaxPool2d(2, stride=2)
avg_polling = nn.AvgPool2d(2, stride=2)

In [5]:
data = torch.randn(1, 1, 4, 4)
data

tensor([[[[ 1.8317,  0.6456, -0.2348, -0.7823],
          [ 0.8336, -1.2270, -0.7989,  0.0294],
          [-0.5602,  1.2931,  1.1798, -0.1490],
          [ 1.6292, -0.0306,  0.7750,  1.2341]]]])

In [6]:
max_pooling(data)

tensor([[[[1.8317, 0.0294],
          [1.6292, 1.2341]]]])

In [7]:
avg_polling(data)

tensor([[[[ 0.5210, -0.4467],
          [ 0.5829,  0.7600]]]])

In [8]:
max_pooling(data).shape

torch.Size([1, 1, 2, 2])

### Dropout

In [18]:
In = torch.randn(2, 64, 7, 7)
np.count_nonzero(In.numpy())

6272

In [12]:
dropout = nn.Dropout(.5, inplace=True)

In [17]:
np.count_nonzero(dropout(In).numpy())

3159